
title: "Silvino Rodrigues"
url: "https://silvinorodrigues.com"
description: >- # this means to ignore newlines until next back-indented value
  Silvino Rodrigues
# baseurl: ""
timezone: "Australia/Sydney"
encoding: utf-8
lang: en-AU
date_format: "%-d %b %Y"

# more Meta
name: Variant Minds
color:
  theme: '#30939e'
  background: transparent
excerpt_separator: '<!--more-->'

## Building
show_drafts: false
future: false
unpublished: false
debug: false

liquid:
  error_mode: strict

sass:
  load_paths:
    - _sass
  sass_dir: assets/css
  # *** PROD: Nice and tight ***
  sourcemap: never
  style: compressed
  quiet_deps: true

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '.sass-cache/'
  - '.jekyll-cache/'
  - 'gemfiles/'

include:
  ## --- from theme ---
  - '404.html'
  - 'site.webmanifest'
  - 'sitemap.xsl'

plugins:
  ## ... More ...
  - jekyll-feed
  - jekyll-sitemap
  # - jemoji
  # - jekyll-avatar
  - jekyll-last-modified-at
  # - jekyll-toc
  # - jekyll-email-protect
  - jekyll-seo-tag

## --- jekyll-category-pages config ---
# category_path: .
# category_layout: my-category.html

## --- jekyll-seo-tag ---
# See: https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md
tagline: Silvino Rodrigues, Author & Neurodivergent Advocate
